[build]
  functions = "functions"   
  publish = "frontend"        

[[redirects]]
  from = "/api/get-code"     
  to = "/.netlify/functions/get-code"
  status = 200

[[redirects]]
  from = "/api/remove-code"   
  to = "/.netlify/functions/remove-code"
  status = 200
