[build]
  publish = "frontend"   
  functions = "functions"

[[redirects]]
  from = "./functions/get-code"
  to = "/.netlify/functions/get-code"
  status = 200

[[redirects]]
  from = "./functions/remove-code"
  to = "/.netlify/functions/remove-code"
  status = 200
