[build]
  publish = "frontend"   
  functions = "functions" 

[[functions]]
  included_files = ["functions/codes.json"]  # Asegúrate de incluir el archivo JSON

[[redirects]]
  from = "/api/get-code"
  to = "/.netlify/functions/get-code"
  status = 200

[[redirects]]
  from = "/api/remove-code"
  to = "/.netlify/functions/remove-code"
  status = 200
